import type { RawOffer, Source } from "./types";

const now = "2026-01-01T00:00:00.000Z";

export const seedSources: Source[] = [
  {
    id: "ai666-gmail-wholesale",
    name: "T佬的gmail批发渠道",
    baseUrl: "https://ai666.dnxb.cc",
    entryUrl: "https://ai666.dnxb.cc/",
    collectionMethod: "http",
    collectorKind: "kami",
    enabled: true,
    notes: "公开商品接口，可自动采集 Gmail 批发价格与库存。",
    updatedAt: now,
  },
  {
    id: "aisou-pro",
    name: "Aisou智充",
    baseUrl: "https://aisou.pro",
    entryUrl: "https://aisou.pro/",
    collectionMethod: "http",
    collectorKind: "kami",
    enabled: true,
    notes: "前端动态加载，适合半自动浏览器采集。",
    updatedAt: now,
  },
  {
    id: "auto-subscribe",
    name: "Auto Subscribe",
    baseUrl: "https://shop.auto-subscribe.com",
    entryUrl: "https://shop.auto-subscribe.com/",
    collectionMethod: "http",
    collectorKind: "dujiao",
    enabled: true,
    notes: "前端页面，首版使用本机浏览器采集。",
    updatedAt: now,
  },
  {
    id: "qxvx-pay",
    name: "QXVX Pay",
    baseUrl: "https://pay.qxvx.cn",
    entryUrl: "https://pay.qxvx.cn/",
    collectionMethod: "http",
    collectorKind: "shopApi",
    enabled: true,
    notes: "待采集确认。",
    updatedAt: now,
  },
  {
    id: "ldxp-jinyao",
    name: "LDXP 金钥",
    baseUrl: "https://pay.ldxp.cn",
    entryUrl: "https://pay.ldxp.cn/shop/jinyao",
    collectionMethod: "http",
    collectorKind: "shopApi",
    enabled: true,
    notes: "可能出现 WAF，无法公开读取时进入采集器待办。",
    updatedAt: now,
  },
  {
    id: "opensora-aifk",
    name: "AUTO FK",
    baseUrl: "https://aifk.opensora.de",
    entryUrl: "https://aifk.opensora.de/",
    collectionMethod: "http",
    collectorKind: "opensoraHtml",
    enabled: true,
    notes: "公开页面能读到部分商品、价格和库存。",
    updatedAt: now,
  },
  {
    id: "caowo-store",
    name: "GPT专卖-cw",
    baseUrl: "https://caowo.store",
    entryUrl: "https://caowo.store/",
    collectionMethod: "http",
    collectorKind: "kami",
    enabled: true,
    notes: "页面动态加载。",
    updatedAt: now,
  },
  {
    id: "makerich-club",
    name: "AI创富俱乐部",
    baseUrl: "https://makerich.club",
    entryUrl: "https://makerich.club/",
    collectionMethod: "http",
    collectorKind: "makerichHtml",
    enabled: true,
    notes: "公开页面可读到推荐商品。",
    updatedAt: now,
  },
  {
    id: "ldxp-pixelshop",
    name: "LDXP Pixelshop",
    baseUrl: "https://pay.ldxp.cn",
    entryUrl: "https://pay.ldxp.cn/shop/pixelshop",
    collectionMethod: "http",
    collectorKind: "shopApi",
    enabled: true,
    notes: "可能出现 WAF，无法公开读取时进入采集器待办。",
    updatedAt: now,
  },
  {
    id: "beibei-demo",
    name: "Beibei 示例渠道",
    baseUrl: "https://bei-bei.shop",
    entryUrl: "https://bei-bei.shop/",
    collectionMethod: "http",
    collectorKind: "beibeiHtml",
    enabled: true,
    notes: "示例渠道，用于演示多来源报价结构。",
    updatedAt: now,
  },
];

export const seedRawOffers: RawOffer[] = [
  {
    id: "sample-beibei-plus",
    sourceId: "beibei-demo",
    sourceName: "Beibei 示例渠道",
    sourceStoreName: "beibei",
    sourceTitle: "ChatGPT Plus 月卡 直冲卡密【质保7天】【自动发货】",
    price: 42,
    currency: "CNY",
    status: "in_stock",
    url: "https://bei-bei.shop/products/chatgpt-plus-dujia",
    tags: [],
    capturedAt: now,
    sourceUpdatedAt: now,
  },
  {
    id: "sample-ldxp-plus-account",
    sourceId: "ldxp-jinyao",
    sourceName: "LDXP 金钥",
    sourceStoreName: "LDXP 极速AI",
    sourceTitle: "GPT Plus成品号(月付/无质保)",
    price: 30,
    currency: "CNY",
    status: "in_stock",
    url: "https://pay.ldxp.cn/item/vf1koi",
    tags: ["无质保"],
    capturedAt: now,
    sourceUpdatedAt: now,
  },
  {
    id: "sample-ldxp-pro5x",
    sourceId: "ldxp-jinyao",
    sourceName: "LDXP 金钥",
    sourceStoreName: "LDXP gpt、gemini账号优惠AI",
    sourceTitle: "Chatgpt PRO x5 代开/续费一个月（无质保）渠道二",
    price: 154,
    currency: "CNY",
    status: "out_of_stock",
    url: "https://pay.ldxp.cn/item/85ar9n",
    tags: ["无质保"],
    capturedAt: now,
    sourceUpdatedAt: now,
  },
  {
    id: "sample-ldxp-codex-api",
    sourceId: "ldxp-jinyao",
    sourceName: "LDXP 金钥",
    sourceStoreName: "LDXP 极速AI",
    sourceTitle: "CodexAPI 500刀额度 不限时",
    price: 46.88,
    currency: "CNY",
    status: "in_stock",
    url: "https://pay.ldxp.cn/item/9mb9pv",
    tags: [],
    capturedAt: now,
    sourceUpdatedAt: now,
  },
  {
    id: "sample-opensora-plus-cdk",
    sourceId: "opensora-aifk",
    sourceName: "AUTO FK",
    sourceStoreName: "AUTO FK",
    sourceTitle: "ChatGPT PLUS 自助充值卡密一个月 [无质保]",
    price: 10,
    currency: "CNY",
    status: "out_of_stock",
    url: "https://aifk.opensora.de/",
    tags: ["无质保"],
    stockCount: 0,
    capturedAt: now,
    sourceUpdatedAt: now,
  },
  {
    id: "sample-makerich-pro20x",
    sourceId: "makerich-club",
    sourceName: "AI创富俱乐部",
    sourceStoreName: "AI创富俱乐部",
    sourceTitle: "ChatGPT PRO 20x充值 ｜200美元 GPT PRO代充",
    price: 275,
    currency: "CNY",
    status: "out_of_stock",
    url: "https://makerich.club/",
    tags: [],
    stockCount: 0,
    capturedAt: now,
    sourceUpdatedAt: now,
  },
  {
    id: "sample-makerich-grok",
    sourceId: "makerich-club",
    sourceName: "AI创富俱乐部",
    sourceStoreName: "AI创富俱乐部",
    sourceTitle: "SuperGrok 独享账号 | 30美金订阅成品号",
    price: 50,
    currency: "CNY",
    status: "out_of_stock",
    url: "https://makerich.club/",
    tags: [],
    stockCount: 0,
    capturedAt: now,
    sourceUpdatedAt: now,
  },
  {
    id: "sample-ldxp-gemini",
    sourceId: "ldxp-pixelshop",
    sourceName: "LDXP Pixelshop",
    sourceStoreName: "彩虹马的AI店",
    sourceTitle: "Gemini pro一年CDK充值 包绑卡 1次",
    price: 10,
    currency: "CNY",
    status: "in_stock",
    url: "https://pay.ldxp.cn/item/wlt656",
    tags: [],
    capturedAt: now,
    sourceUpdatedAt: now,
  },
  {
    id: "sample-auto-subscribe-claude",
    sourceId: "auto-subscribe",
    sourceName: "Auto Subscribe",
    sourceStoreName: "RedeemGPT",
    sourceTitle: "Claude Pro （$20/月）自助卡密",
    price: 105,
    currency: "CNY",
    status: "low_stock",
    url: "https://talkai.cyou/item/29",
    tags: [],
    capturedAt: now,
    sourceUpdatedAt: now,
  },
  {
    id: "sample-makerich-google",
    sourceId: "makerich-club",
    sourceName: "AI创富俱乐部",
    sourceStoreName: "makerich",
    sourceTitle: "稳定老号 Google 普号｜美区老号",
    price: 7.5,
    currency: "CNY",
    status: "out_of_stock",
    url: "https://makerich.club/",
    tags: [],
    capturedAt: now,
    sourceUpdatedAt: now,
  },
];
